Apps/Auth/urls.py
from django.urls import path
from Apps.Auth import views



app_name = 'Auth'

urlpatterns = [

    path('signup/', views.Signup.as_view(template_name='Auth/signup.html'), name='Signup'),
    path('confirm-signup/', views.ConfirmSignup.as_view(template_name='Auth/confirm-signup.html'), name='Confirm-Signup'),

    path('login/', views.Login.as_view(template_name='Auth/login.html'), name='Login'),
    path('login-as-guest/', views.LoginAsGuest.as_view(), name='Guest-Login'),
    path('logout/', views.Logout.as_view(), name='Logout'),

    path('forget-password/', views.ForgetPassword.as_view(template_name='Auth/forget-password.html'), name='Forget-Password'),
    path('reset-password/', views.ResetPassword.as_view(template_name='Auth/reset-password.html'), name='Reset-Password'),
]

Apps/Chat/api/urls.py
from django.urls import path, include
from . import views


app_name = 'Chat.api'

urlpatterns = [

    path('<slug:Room_Code>/', include([

        path('join/', views.JoinRoomAPI.as_view(), name='Join-Room'),

        path('settings/', include([

            path('cover/', views.RoomCoverSettingsAPI.as_view(), name='Cover-Settings'),

            path('', views.RoomSettingsAPI.as_view(), name='Settings'),
        ])),

        path('members/', include([

            path('<int:Member_id>/', views.MemberAPI.as_view(), name='Member'),

            path('', views.MembersAPI.as_view(), name='Members'),
        ])),

        path('messages/', views.MessagesAPI.as_view(), name='Messages'),

        path('', views.RoomAPI.as_view(), name='Room'),
    ])),

    path('', views.RoomsAPI.as_view(), name='Rooms'),
]

Apps/Chat/urls.py
from django.urls import path, include
from . import views



app_name = 'Chat'

urlpatterns = [

    path('create/', views.CreateRoomView.as_view(template_name='Chat/Create.html'), name='Create'),

    path('room/', views.JoinRoomView.as_view(), name='Join-Room'),

    path('<slug:Room_Code>/', include([

        path('settings/', views.SettingsView.as_view(template_name='Chat/Settings.html'), name='Settings'),

        path('members/', include([

            path('<int:Member_id>/', views.MemberView.as_view(), name='Member'),

            path('', views.MembersView.as_view(template_name='Chat/Members.html'), name='Members'),
        ])),

        path('', views.RoomView.as_view(template_name='Chat/Room.html'), name='Room'),
    ])),
    
    path('', views.HomeView.as_view(template_name='Chat/Home.html'), name='Home')
]

Apps/Profile/urls.py
from django.urls import path
from . import views



app_name = 'Profile'

urlpatterns = [

    path('password/', views.PasswordView.as_view(template_name='Profile/Password.html'), name='Password'),

    path('settings/', views.SettingsView.as_view(template_name='Profile/Settings.html'), name='Settings'),

    path('', views.ProfileView.as_view(template_name='Profile/Profile.html'), name='Profile'),
]

WebChat/urls.py
import os
from django.apps import apps
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from Apps.Info import views


urlpatterns = [
    path('admin/', admin.site.urls),

    path('auth/', include('Apps.Auth.urls')),

    path('profile/', include('Apps.Profile.urls')),

    path('info/', include('Apps.Info.urls')),

    path('chats/', include('Apps.Chat.urls')),

    path('api/', include([

        path('auth/', include('Apps.Auth.api.urls')),

        path('profile/', include('Apps.Profile.api.urls')),

        path('info/', include('Apps.Info.api.urls')),

        path('chats/', include('Apps.Chat.api.urls')),

    ])),

    path('', views.HomeView.as_view(template_name='Info/Home.html'), name=''),
]

urlpatterns += static(
    settings.MEDIA_URL + 'user/',
    document_root=os.path.join(apps.get_app_config('Profile').path, 'media', 'user'),
)

urlpatterns += static(
    settings.MEDIA_URL + 'rooms/',
    document_root=os.path.join(apps.get_app_config('Chat').path, 'media', 'rooms'),
)

Apps/Info/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _



class Feedback(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(_('Feedback Title'), max_length=100)
    feedback = models.CharField(_('Feedback'), max_length=1000)
    is_deleted = models.BooleanField(_('Is Feedback Deleted'), default=False)
    created_at = models.DateTimeField(_('Feedback Creation Date'), auto_now_add=True)

Apps/Profile/models.py
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import User
from django.db import models
from .storages import default_storage



def user_directory_path(instance, filename):
    return 'user/{0}'.format(filename)


class Profile(models.Model):

    class Gender(models.TextChoices):
        MALE = 'M', _('Male Gender')
        FEMALE = 'F', _('Female Gender')
        Unknown = 'U', _('Unknown Gender')

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(_('Profile Picture'), storage=default_storage(),\
        upload_to=user_directory_path, default='user/User.png')
    bio = models.CharField(_('Bio'), max_length=100, null=True, blank=True)
    birthday = models.DateField(_('Birthday Date'), null=True, blank=True)
    gender = models.CharField(_('Gender'), max_length=2, choices=Gender.choices, default=Gender.Unknown)
    phone = models.CharField(max_length=32, null=True, blank=True)
    address = models.CharField(max_length=255, null=True, blank=True)
    country = models.CharField(max_length=50, null=True, blank=True)
    city = models.CharField(max_length=50, null=True, blank=True)
    zip = models.CharField(max_length=30, null=True, blank=True)

    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def save_old_image_path(self):
        self.__File_Name = self.avatar.name
        self.__File_Path = self.avatar.path if self.avatar.name else ''
    
    def get_old_image_path(self):
        return self.__File_Path
    
    def get_old_image_name(self):
        return self.__File_Name

Apps/Chat/channels/forms.py
from django import forms



class MessagesForm(forms.Form):
    message = forms.CharField(max_length=1000, min_length=1, required=True)

Apps/Chat/forms.py
from django import forms


class JoinRoomForm(forms.Form):
    password = forms.CharField(min_length=1, max_length=100, required=True)

Apps/Chat/api/views.py
from django.db import transaction
from django.contrib.auth.hashers import make_password, check_password
from django.db.models import Subquery, OuterRef
from django.core.files.storage import default_storage
from rest_framework import exceptions
from rest_framework.generics import ListCreateAPIView, ListAPIView, RetrieveUpdateAPIView, UpdateAPIView, \
    RetrieveAPIView, RetrieveUpdateDestroyAPIView
from ..models import Members, Room, Messages
from .paginator import RoomsPaginator, MessagesPaginator, MembersPaginator
from .mixins import BaseChatAPI, RoomMixin, MemberMixin
from .serializers import (
    RoomsSerializer,
    RoomSettingsSerializer,
    JoinRoomSerializer,
    RoomCoverSerializer,
    RoomSerializer,
    MembersSerializer,
    MemberSerializer,
    MessagesSerializer
)


class RoomsAPI(BaseChatAPI, ListCreateAPIView):
    throttle_scope = 'rooms', '100/min'
    serializer_class = RoomsSerializer
    pagination_class = RoomsPaginator

    def get_queryset(self):
        return Room.objects.filter(id__in=Subquery(
            Members.objects\
                .filter(user=self.request.user, room=OuterRef('id'), is_pending=False, is_deleted=False) \
                .values_list('room')
        ), is_deleted=False).order_by('-id')

    def perform_create(self, serializer):
        with transaction.atomic():
            _room = serializer.save(
                creator=self.request.user,
                password=make_password(serializer.validated_data['password'])
            )
            Members(user=self.request.user, room=_room, is_admin=True, is_pending=False).save()


class JoinRoomAPI(BaseChatAPI, RetrieveUpdateAPIView):
    throttle_scope = 'join-room', '100/min'
    serializer_class = JoinRoomSerializer

    queryset = Room.objects.filter(is_closed=False, is_deleted=False).all()
    lookup_field = 'code'
    lookup_url_kwarg = 'Room_Code'

    def perform_update(self, serializer):
        if not check_password(serializer.validated_data['password'], serializer.instance.password):
            raise exceptions.PermissionDenied(detail='Wrong Password')
        
        if not Members.objects.filter(user=self.request.user, room=serializer.instance).exists():
            Members(
                user=self.request.user, room=serializer.instance,
                is_pending = True if serializer.instance.need_permission else False
            )


class RoomSettingsAPI(BaseChatAPI, RoomMixin, RetrieveUpdateAPIView):
    throttle_scope = 'room-settings', '100/min'
    serializer_class = RoomSettingsSerializer

    is_admin = True
    need_room_object = True
    
    def perform_update(self, serializer):
        if 'password' in serializer.validated_data:
            serializer.validated_data['password'] = make_password(serializer.validated_data['password'])
        serializer.save()


class RoomCoverSettingsAPI(BaseChatAPI, RoomMixin, UpdateAPIView):
    throttle_scope = 'room-cover-settings', '100/min'
    serializer_class = RoomCoverSerializer

    is_admin = True
    need_room_object = True
    
    def perform_update(self, serializer):
        if 'cover' in serializer.validated_data:
            if self.room.get_old_image_name() != serializer.validated_data['cover'] and (
                self.room.get_old_image_name() != 'rooms/defaultCover.jpg'
            ):
                default_storage.delete(self.room.get_old_image_path())
            serializer.save()


class RoomAPI(BaseChatAPI, RoomMixin, RetrieveAPIView):
    throttle_scope = 'room', '100/min'
    serializer_class = RoomSerializer
    need_room_object = True


class MembersAPI(BaseChatAPI, RoomMixin, ListAPIView):
    throttle_scope = 'members', '100/min'
    serializer_class = MembersSerializer
    pagination_class = MembersPaginator

    is_admin = True

    def get_queryset(self):
        return Members.objects.filter(is_deleted=False, room=self.room)


class MemberAPI(BaseChatAPI, MemberMixin, RoomMixin, RetrieveUpdateDestroyAPIView):
    throttle_scope = 'member', '100/min'
    serializer_class = MemberSerializer
    
    is_admin = True
    need_member_object = True
    
    def perform_update(self, serializer):
        serializer.save(
            is_admin=True if 'upgrade' in self.request.query_params else serializer.instance.is_admin,
            is_pending=serializer.instance.is_pending if 'upgrade' in self.request.query_params else False
        )

    def perform_destroy(self, instance: Members):
        if self.room.creator == self.request_member.user:
            raise exceptions.PermissionDenied(detail='Is Creator')
        
        elif self.request_member.is_admin and not self.is_creator():
            raise exceptions.PermissionDenied(detail='Is Admin')

        
        if 'degrade' in self.request.query_params:
            self.request_member.is_admin = False
        else:
            self.request_member.is_deleted = True
            
        self.request_member.save()


class MessagesAPI(BaseChatAPI, RoomMixin, ListAPIView):
    throttle_scope = 'messages', '100/min'
    serializer_class = MessagesSerializer
    pagination_class = MessagesPaginator

    def get_queryset(self):
        return Messages.objects.filter(is_deleted=False, room=self.room)

Apps/Chat/views.py
from braces import views
from django.views.generic import TemplateView, CreateView, UpdateView, ListView, View
from django.contrib.auth.hashers import make_password, check_password
from django.core.files.storage import default_storage
from django.urls import reverse_lazy as reverse
from django.db.models import Subquery, OuterRef
from django.db import transaction
from django.utils import timezone
from Apps.Profile.mixins import ProfileMixin
from Apps.Auth.mixins import SuccessMessageMixin
from .mixins import RoomMixin, LoginRequiredMixin, MemberMixin
from .models import Room, Members, Messages
from .forms import JoinRoomForm



class HomeView(LoginRequiredMixin, ProfileMixin, ListView):

    def get_queryset(self):
        return Room.objects.filter(id__in=Subquery(
            Members.objects.\
                filter(user=self.request.user, room=OuterRef('id'), is_pending=False, is_deleted=False) \
                .values_list('room')
        ), is_deleted=False).order_by('-id')


class CreateRoomView(LoginRequiredMixin, ProfileMixin, SuccessMessageMixin, CreateView):
    success_flash_message_name = 'create_room'
    success_flash_message = 'Your Room Created Successfully'

    success_url = reverse('Chat:Home')
    
    model = Room
    fields = ['name', 'password', 'description', 'cover']

    def form_valid(self, form):
        room = form.save(commit=False)
        room.creator = self.request.user
        room.password = make_password(room.password if room.password else '')
        with transaction.atomic():
            room.save()
            Members(user=self.request.user, room=room, is_admin=True, is_pending=False).save()
        return super().form_valid(form)


class RoomView(LoginRequiredMixin, ProfileMixin, RoomMixin, TemplateView):

    def get_context_data(self, **kwargs):
        members = Members.objects.filter(room=self.room, is_deleted=False, is_pending=False)\
            .prefetch_related('user__profile')
        room_messages = Messages.objects.filter(room=self.room, is_deleted=False)\
            .prefetch_related('user__profile')
        return super().get_context_data(room_messages=room_messages, members=members, **kwargs)


class JoinRoomView(LoginRequiredMixin, views.JSONResponseMixin, View):

    def get(self, request, *args, **kwargs):
        _Exists = Room.objects.filter(code=request.GET.get('code'), is_deleted=False)\
            .filter(is_closed=False).exists()
        return self.render_json_response({}, status=200 if _Exists else 404)
    
    def post(self, request, *args, **kwargs):
        _Form = JoinRoomForm(request.POST)
        if not _Form.is_valid():
            return self.render_json_response(_Form.errors, status=400)

        _Room = Room.objects.filter(code=request.GET.get('code'), is_deleted=False)\
            .filter(is_closed=False).first()
            
        if _Room is None:
            return self.render_json_response({}, status=404)
        
        elif not check_password(_Form.cleaned_data['password'], _Room.password):
            return self.render_json_response({}, status=403)

        elif Members.objects.filter(user=request.user, room=_Room).exists():
            return self.render_json_response({}, status=200)
        
        Members(user=request.user, room=_Room, is_pending=True if _Room.need_permission else False).save()
        return self.render_json_response({}, status=201)


class SettingsView(LoginRequiredMixin, ProfileMixin, RoomMixin, SuccessMessageMixin, UpdateView):

    success_flash_message_name = 'update_room'
    success_flash_message = 'Your Room Updated Successfully'

    is_admin = True

    model = Room
    fields = ['name', 'description', 'is_closed', 'need_permission', 'password', 'cover']

    def get_success_url(self):
        return reverse('Chat:Settings', kwargs={'Room_Code': self.room.code})

    def get_object(self, *args, **kwargs):
        self.room.save_old_image_path()
        return self.room
    
    def form_valid(self, form):
        _Room = form.save(commit=False)
        if _Room.get_old_image_name() != form.cleaned_data['cover'] and (
            _Room.get_old_image_name() != 'rooms/defaultCover.jpg'
        ):
            default_storage.delete(_Room.get_old_image_path())

        _Room.password = make_password(form.cleaned_data['password'])
        _Room.last_updated = timezone.now()
        _Room.save()
        return super().form_valid(form)


class MembersView(LoginRequiredMixin, ProfileMixin, RoomMixin, ListView):

    is_admin = True

    def get_queryset(self):
        return Members.objects.filter(room=self.room, is_deleted=False).select_related('user')\
            .prefetch_related('user__profile')


class MemberView(LoginRequiredMixin, ProfileMixin, RoomMixin, MemberMixin, views.JSONResponseMixin, View):

    is_admin = True

    def patch(self, request, Room_Code, Member_id):
        if 'upgrade' in request.GET:
            self.Request_Member.is_admin = True
        else:
            self.Request_Member.is_pending = False
        self.Request_Member.save()
        return self.render_json_response({})


    def delete(self, request, Room_Code, Member_id):
        if self.room.creator == self.Request_Member.user:
            return self.render_json_response({'error': 'Is Creator'}, 403)
        
        elif self.Request_Member.is_admin and not self.is_creator():
            return self.render_json_response({'error': 'Is Admin'}, 403)
        
        if 'degrade' in request.GET:
            self.Request_Member.is_admin = False
        else:
            self.Request_Member.is_deleted = True
            
        self.Request_Member.save()
        return self.render_json_response({}, 204)

Apps/Chat/templates/Chat/shared/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css" integrity="sha512-mSYUmp1HYZDFaVKK//63EcZq4iFWFjxSL+Z3T/aCt4IO9Cejm03q3NKKYN6pFQzY0SBOr8h+eCIAZHPXcpZaNw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    
    <link href="{% static 'fontawesomefree/css/all.min.css' %}" rel="stylesheet" type="text/css">

    <link type="text/css" href="{% static 'Chat/notyf/notyf.min.css' %}" rel="stylesheet">

    <link rel="icon" href="{% static 'Chat/images/favicon.ico' %}">

    {% block styles %}{% endblock %}


    <!-- Bootstrap CSS -->

    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>

    {% include 'Chat/shared/navbar.html' %}

    <div class="container">

        {% block content %}{% endblock %}

        <br /><br /><br />

    </div>



    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <!--<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.js" integrity="sha512-n/4gHW3atM3QqRcbCn6ewmpxcLAHGaDjpEBu4xZd47N0W2oQ+6q7oc3PXstrJYXcbNU1OHdQ1T7pAP+gi5Yu8g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js" integrity="sha512-T/tUfKSV1bihCnd+MxKD0Hm1uBBroVYBOYSk1knyvQ9VyZJpc/ALb4P0r6ubwVPSGB2GvjeoMAJJImBG12TiaQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js" integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2" crossorigin="anonymous"></script>
    -->


    
    {% block scripts %}{% endblock %}

  </body>
</html>

Apps/Chat/templates/Chat/shared/model.html
<button type="button" id="ChangedButton" class="btn btn-primary" style="display: none;"
    data-toggle="modal" data-target="#Changed"></button>

<!-- Modal -->
<div class="modal fade" id="Changed" tabindex="-1" aria-labelledby="ChangedLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="ChangedLabel">Message</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          {{ ModelMessage }}
        </div>
      </div>
    </div>
</div>


<script>
  document.addEventListener('DOMContentLoaded', () => {
    _Model = document.getElementById('Changed');
    if (_Model != null){
        document.getElementById('ChangedButton').click();
    }
  }, false);
</script>

Apps/Chat/templates/Chat/shared/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'Chat:Home' %}">Chats</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'Chat:Create' %}">Create Room <span class="sr-only">(current)</span></a>
        </li>
      </ul>
      <div class="form-inline my-2 my-lg-0">

        <div class="spinner-border text-light" role="status" id="SearchSpinner">
          <span class="sr-only">Loading...</span>
        </div>
        <span style="margin: 5px;"></span>
        <input class="form-control mr-sm-2" type="search" placeholder="Enter Room Code"
          id="RoomSearch" aria-label="Search" Join-Room-Url="{% url 'Chat:Join-Room' %}">

        <ul class="navbar-nav">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Hello {{ request.user.get_short_name }} 
              <img src="{{ profile.avatar.url }}" width="30" height="30" class="rounded-circle">
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink" style="position: fixed; right: 10px;top: auto; left: auto;">
              <a class="dropdown-item" href="{% url '' %}">Dashboard</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'Profile:Profile' %}">Edit Profile</a>
              <a class="dropdown-item" href="{% url 'Profile:Password' %}">Change Password</a>
              <a class="dropdown-item" href="{% url 'Profile:Settings' %}">Settings</a>
              {% if request.user.is_superuser %}
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'admin:index' %}">Admin Dashboard</a>
              {% endif %}
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'Auth:Login' %}">Switch Account</a>
              <a class="dropdown-item" href="{% url 'Auth:Logout' %}">Log Out</a>
            </div>
          </li>
        </ul>

      </div>
    </div>
</nav>



<button type="button" id="MessageModelButton" class="btn btn-primary" style="display: none;"
data-toggle="modal" data-target="#MessageModel"></button>

<!-- Modal -->
<div class="modal fade" id="MessageModel" tabindex="-1" aria-labelledby="MessageModelLabel" aria-hidden="true">
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title" id="MessageModelLabel"></h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body" id="MessageModelData"></div>
  </div>
</div>
</div>


{% csrf_token %}


<script>
  document.addEventListener('DOMContentLoaded', () => {

    document.getElementById('SearchSpinner').style.display = 'none';
    
    var _isSearching = false;

    document.getElementById('RoomSearch').onkeydown = (event) => {

      if (event.keyCode != 13){
        return ;
      }
      else if (event.target.value < 1){
        return ;
      }
      else if (_isSearching){
        return ;
      }

      _JoinRoomUrl = event.target.getAttribute('Join-Room-Url')
      if (!_JoinRoomUrl){
        return ;
      }

      _isSearching = true;
      document.getElementById('SearchSpinner').style.display = '';

      $.ajax(_JoinRoomUrl, {
        
        type: 'GET',

        headers: { 
            "X-CSRFToken": document.getElementsByName('csrfmiddlewaretoken')[0].value
        },

        dataType: 'json',

        data: {
          'code': event.target.value
        },

        success: function (data, status, xhr) {

          console.log(data)
          console.log(status)
          console.log(xhr)

          _isSearching = false;
          document.getElementById('SearchSpinner').style.display = 'none';

          document.getElementById('MessageModelLabel').innerText = 'Join Room';

          document.getElementById('MessageModelData').innerText = '';

          document.getElementById('MessageModelData').appendChild(
            (() => {

              _Password = document.createElement('input');
              _Password.classList.add('form-control');
              _Password.setAttribute('type', 'password');
              _Password.setAttribute('id', 'RoomPassword');
              _Password.setAttribute('placeholder', 'Enter Room Password');

              return _Password

            })()
          )

          document.getElementById('MessageModelData').appendChild(
            document.createElement('br')
          )

          document.getElementById('MessageModelData').appendChild(
            (() => {

              _Button = document.createElement('button');
              _Button.classList.add('btn');
              _Button.classList.add('btn-success');
              _Button.innerText = 'Join Room'
              _Button.onclick = (event) => {

                $.ajax(_JoinRoomUrl + '?code=' + document.getElementById('RoomSearch').value, {
        
                  type: 'POST',

                  headers: { 
                      "X-CSRFToken": document.getElementsByName('csrfmiddlewaretoken')[0].value
                  },

                  dataType: 'json',

                  data: {
                    'password': document.getElementById('RoomPassword').value
                  },

                  success: function (data, status, xhr) {

                    console.log(data)
                    console.log(status)
                    console.log(xhr)

                    _isSearching = false;
                    document.getElementById('MessageModelLabel').innerText = 'Success';
                    document.getElementById('MessageModelData').style.color = '';
                    document.getElementById('MessageModelData').innerText = 'Success  Joining Room';
                  },

                  error: function (jqXhr, textStatus, errorMessage) {
                    console.log(errorMessage);
                    console.log(textStatus);
                    console.log(jqXhr);
                    
                    _isSearching = false;
                    document.getElementById('MessageModelLabel').innerText = 'Error';
                    document.getElementById('MessageModelData').style.color = 'red';
                    document.getElementById('MessageModelData').innerText = 'Error in Joining Room Or Wrong Password';
                  }

                })
              }

              return _Button

            })()
          )
          document.getElementById('MessageModelButton').click();
        },

        error: function (jqXhr, textStatus, errorMessage) {
          console.log(errorMessage);
          console.log(textStatus);
          console.log(jqXhr);
          
          _isSearching = false;
          document.getElementById('MessageModelLabel').innerText = 'Error';
          document.getElementById('SearchSpinner').style.display = 'none';
          document.getElementById('MessageModelData').style.color = 'red';
          document.getElementById('MessageModelData').innerText = 'Room Not Found';
          document.getElementById('MessageModelButton').click();
        }

      })
    }

  }, false);
</script>