Apps/Chat/api/urls.py
from django.urls import path, include
from . import views


app_name = 'Chat.api'

urlpatterns = [

    path('<slug:Room_Code>/', include([

        path('join/', views.JoinRoomAPI.as_view(), name='Join-Room'),

        path('settings/', include([

            path('cover/', views.RoomCoverSettingsAPI.as_view(), name='Cover-Settings'),

            path('', views.RoomSettingsAPI.as_view(), name='Settings'),
        ])),

        path('members/', include([

            path('<int:Member_id>/', views.MemberAPI.as_view(), name='Member'),

            path('', views.MembersAPI.as_view(), name='Members'),
        ])),

        path('messages/', views.MessagesAPI.as_view(), name='Messages'),

        path('', views.RoomAPI.as_view(), name='Room'),
    ])),

    path('', views.RoomsAPI.as_view(), name='Rooms'),
]

Apps/Chat/urls.py
from django.urls import path, include
from . import views



app_name = 'Chat'

urlpatterns = [

    path('create/', views.CreateRoomView.as_view(template_name='Chat/Create.html'), name='Create'),

    path('room/', views.JoinRoomView.as_view(), name='Join-Room'),

    path('<slug:Room_Code>/', include([

        path('settings/', views.SettingsView.as_view(template_name='Chat/Settings.html'), name='Settings'),

        path('members/', include([

            path('<int:Member_id>/', views.MemberView.as_view(), name='Member'),

            path('', views.MembersView.as_view(template_name='Chat/Members.html'), name='Members'),
        ])),

        path('', views.RoomView.as_view(template_name='Chat/Room.html'), name='Room'),
    ])),
    
    path('', views.HomeView.as_view(template_name='Chat/Home.html'), name='Home')
]

WebChat/urls.py
import os
from django.apps import apps
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from Apps.Info import views


urlpatterns = [
    path('admin/', admin.site.urls),

    path('auth/', include('Apps.Auth.urls')),

    path('profile/', include('Apps.Profile.urls')),

    path('info/', include('Apps.Info.urls')),

    path('chats/', include('Apps.Chat.urls')),

    path('api/', include([

        path('auth/', include('Apps.Auth.api.urls')),

        path('profile/', include('Apps.Profile.api.urls')),

        path('info/', include('Apps.Info.api.urls')),

        path('chats/', include('Apps.Chat.api.urls')),

    ])),

    path('', views.HomeView.as_view(template_name='Info/Home.html'), name=''),
]

urlpatterns += static(
    settings.MEDIA_URL + 'user/',
    document_root=os.path.join(apps.get_app_config('Profile').path, 'media', 'user'),
)

urlpatterns += static(
    settings.MEDIA_URL + 'rooms/',
    document_root=os.path.join(apps.get_app_config('Chat').path, 'media', 'rooms'),
)

Apps/Chat/models.py
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import User
from django.db import models
from .helper import Random
from .storages import default_storage



def user_directory_path(instance, filename):
    return 'rooms/{0}'.format(filename)

def random_code(): return Random.create_random_token(10, 50)



class Room(models.Model):
    creator = models.ForeignKey(User, on_delete=models.CASCADE)

    name = models.CharField(_('Room Name'), max_length=100)
    code = models.CharField(_('Room Code'), max_length=100, unique=True, default=random_code)
    password = models.CharField(_('Room Password'), max_length=100)
    description = models.CharField(_('Room Description'), max_length=1000, null=True, default='')
    
    is_closed = models.BooleanField(_('Is Room Closed'), default=False)
    is_deleted = models.BooleanField(_('Is Room Deleted'), default=False)
    need_permission = models.BooleanField(_('Need Creator Permission To Enter'), default=True)
    cover = models.ImageField(_('Room Cover Image'), storage=default_storage,
        upload_to=user_directory_path, default='rooms/defaultCover.jpg')

    last_updated = models.DateTimeField(_('Room Last Updated Settings'), auto_now=True)
    created_at = models.DateTimeField(_('Room Creation Date'), auto_now_add=True)

    def save_old_image_path(self):
        self.__File_Name = self.cover.name
        self.__File_Path = self.cover.path if self.cover.name else ''
    
    def get_old_image_path(self):
        return self.__File_Path
    
    def get_old_image_name(self):
        return self.__File_Name


class Members(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)

    is_admin = models.BooleanField(_('Is Room Admin'), default=False)
    is_pending = models.BooleanField(_('Is Pending User'), default=True)
    is_deleted = models.BooleanField(_('Is User Deleted'), default=False)

    last_updated = models.DateTimeField(_('Member Last Updated Settings'), auto_now=True)
    created_at = models.DateTimeField(_('Member Creation Date'), auto_now_add=True)


class Messages(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='Message_From_User')
    room = models.ForeignKey(Room, on_delete=models.CASCADE, related_name='Message_Room')

    message = models.CharField(_('Room Message'), max_length=1000, default='')
    is_deleted = models.BooleanField(_('Is User Deleted'), default=False)

    created_at = models.DateTimeField(_('Message Creation Date'), auto_now_add=True)

Apps/Chat/channels/forms.py
from django import forms



class MessagesForm(forms.Form):
    message = forms.CharField(max_length=1000, min_length=1, required=True)

Apps/Chat/forms.py
from django import forms


class JoinRoomForm(forms.Form):
    password = forms.CharField(min_length=1, max_length=100, required=True)

Apps/Chat/api/views.py
from django.db import transaction
from django.contrib.auth.hashers import make_password, check_password
from django.db.models import Subquery, OuterRef
from django.core.files.storage import default_storage
from rest_framework import exceptions
from rest_framework.generics import ListCreateAPIView, ListAPIView, RetrieveUpdateAPIView, UpdateAPIView, \
    RetrieveAPIView, RetrieveUpdateDestroyAPIView
from ..models import Members, Room, Messages
from .paginator import RoomsPaginator, MessagesPaginator, MembersPaginator
from .mixins import BaseChatAPI, RoomMixin, MemberMixin
from .serializers import (
    RoomsSerializer,
    RoomSettingsSerializer,
    JoinRoomSerializer,
    RoomCoverSerializer,
    RoomSerializer,
    MembersSerializer,
    MemberSerializer,
    MessagesSerializer
)


class RoomsAPI(BaseChatAPI, ListCreateAPIView):
    throttle_scope = 'rooms', '100/min'
    serializer_class = RoomsSerializer
    pagination_class = RoomsPaginator

    def get_queryset(self):
        return Room.objects.filter(id__in=Subquery(
            Members.objects\
                .filter(user=self.request.user, room=OuterRef('id'), is_pending=False, is_deleted=False) \
                .values_list('room')
        ), is_deleted=False).order_by('-id')

    def perform_create(self, serializer):
        with transaction.atomic():
            _room = serializer.save(
                creator=self.request.user,
                password=make_password(serializer.validated_data['password'])
            )
            Members(user=self.request.user, room=_room, is_admin=True, is_pending=False).save()


class JoinRoomAPI(BaseChatAPI, RetrieveUpdateAPIView):
    throttle_scope = 'join-room', '100/min'
    serializer_class = JoinRoomSerializer

    queryset = Room.objects.filter(is_closed=False, is_deleted=False).all()
    lookup_field = 'code'
    lookup_url_kwarg = 'Room_Code'

    def perform_update(self, serializer):
        if not check_password(serializer.validated_data['password'], serializer.instance.password):
            raise exceptions.PermissionDenied(detail='Wrong Password')
        
        if not Members.objects.filter(user=self.request.user, room=serializer.instance).exists():
            Members(
                user=self.request.user, room=serializer.instance,
                is_pending = True if serializer.instance.need_permission else False
            )


class RoomSettingsAPI(BaseChatAPI, RoomMixin, RetrieveUpdateAPIView):
    throttle_scope = 'room-settings', '100/min'
    serializer_class = RoomSettingsSerializer

    is_admin = True
    need_room_object = True
    
    def perform_update(self, serializer):
        if 'password' in serializer.validated_data:
            serializer.validated_data['password'] = make_password(serializer.validated_data['password'])
        serializer.save()


class RoomCoverSettingsAPI(BaseChatAPI, RoomMixin, UpdateAPIView):
    throttle_scope = 'room-cover-settings', '100/min'
    serializer_class = RoomCoverSerializer

    is_admin = True
    need_room_object = True
    
    def perform_update(self, serializer):
        if 'cover' in serializer.validated_data:
            if self.room.get_old_image_name() != serializer.validated_data['cover'] and (
                self.room.get_old_image_name() != 'rooms/defaultCover.jpg'
            ):
                default_storage.delete(self.room.get_old_image_path())
            serializer.save()


class RoomAPI(BaseChatAPI, RoomMixin, RetrieveAPIView):
    throttle_scope = 'room', '100/min'
    serializer_class = RoomSerializer
    need_room_object = True


class MembersAPI(BaseChatAPI, RoomMixin, ListAPIView):
    throttle_scope = 'members', '100/min'
    serializer_class = MembersSerializer
    pagination_class = MembersPaginator

    is_admin = True

    def get_queryset(self):
        return Members.objects.filter(is_deleted=False, room=self.room)


class MemberAPI(BaseChatAPI, MemberMixin, RoomMixin, RetrieveUpdateDestroyAPIView):
    throttle_scope = 'member', '100/min'
    serializer_class = MemberSerializer
    
    is_admin = True
    need_member_object = True
    
    def perform_update(self, serializer):
        serializer.save(
            is_admin=True if 'upgrade' in self.request.query_params else serializer.instance.is_admin,
            is_pending=serializer.instance.is_pending if 'upgrade' in self.request.query_params else False
        )

    def perform_destroy(self, instance: Members):
        if self.room.creator == self.request_member.user:
            raise exceptions.PermissionDenied(detail='Is Creator')
        
        elif self.request_member.is_admin and not self.is_creator():
            raise exceptions.PermissionDenied(detail='Is Admin')

        
        if 'degrade' in self.request.query_params:
            self.request_member.is_admin = False
        else:
            self.request_member.is_deleted = True
            
        self.request_member.save()


class MessagesAPI(BaseChatAPI, RoomMixin, ListAPIView):
    throttle_scope = 'messages', '100/min'
    serializer_class = MessagesSerializer
    pagination_class = MessagesPaginator

    def get_queryset(self):
        return Messages.objects.filter(is_deleted=False, room=self.room)

Apps/Chat/views.py
from braces import views
from django.views.generic import TemplateView, CreateView, UpdateView, ListView, View
from django.contrib.auth.hashers import make_password, check_password
from django.core.files.storage import default_storage
from django.urls import reverse_lazy as reverse
from django.db.models import Subquery, OuterRef
from django.db import transaction
from django.utils import timezone
from Apps.Profile.mixins import ProfileMixin
from Apps.Auth.mixins import SuccessMessageMixin
from .mixins import RoomMixin, LoginRequiredMixin, MemberMixin
from .models import Room, Members, Messages
from .forms import JoinRoomForm



class HomeView(LoginRequiredMixin, ProfileMixin, ListView):

    def get_queryset(self):
        return Room.objects.filter(id__in=Subquery(
            Members.objects.\
                filter(user=self.request.user, room=OuterRef('id'), is_pending=False, is_deleted=False) \
                .values_list('room')
        ), is_deleted=False).order_by('-id')


class CreateRoomView(LoginRequiredMixin, ProfileMixin, SuccessMessageMixin, CreateView):
    success_flash_message_name = 'create_room'
    success_flash_message = 'Your Room Created Successfully'

    success_url = reverse('Chat:Home')
    
    model = Room
    fields = ['name', 'password', 'description', 'cover']

    def form_valid(self, form):
        room = form.save(commit=False)
        room.creator = self.request.user
        room.password = make_password(room.password if room.password else '')
        with transaction.atomic():
            room.save()
            Members(user=self.request.user, room=room, is_admin=True, is_pending=False).save()
        return super().form_valid(form)


class RoomView(LoginRequiredMixin, ProfileMixin, RoomMixin, TemplateView):

    def get_context_data(self, **kwargs):
        members = Members.objects.filter(room=self.room, is_deleted=False, is_pending=False)\
            .prefetch_related('user__profile')
        room_messages = Messages.objects.filter(room=self.room, is_deleted=False)\
            .prefetch_related('user__profile')
        return super().get_context_data(room_messages=room_messages, members=members, **kwargs)


class JoinRoomView(LoginRequiredMixin, views.JSONResponseMixin, View):

    def get(self, request, *args, **kwargs):
        _Exists = Room.objects.filter(code=request.GET.get('code'), is_deleted=False)\
            .filter(is_closed=False).exists()
        return self.render_json_response({}, status=200 if _Exists else 404)
    
    def post(self, request, *args, **kwargs):
        _Form = JoinRoomForm(request.POST)
        if not _Form.is_valid():
            return self.render_json_response(_Form.errors, status=400)

        _Room = Room.objects.filter(code=request.GET.get('code'), is_deleted=False)\
            .filter(is_closed=False).first()
            
        if _Room is None:
            return self.render_json_response({}, status=404)
        
        elif not check_password(_Form.cleaned_data['password'], _Room.password):
            return self.render_json_response({}, status=403)

        elif Members.objects.filter(user=request.user, room=_Room).exists():
            return self.render_json_response({}, status=200)
        
        Members(user=request.user, room=_Room, is_pending=True if _Room.need_permission else False).save()
        return self.render_json_response({}, status=201)


class SettingsView(LoginRequiredMixin, ProfileMixin, RoomMixin, SuccessMessageMixin, UpdateView):

    success_flash_message_name = 'update_room'
    success_flash_message = 'Your Room Updated Successfully'

    is_admin = True

    model = Room
    fields = ['name', 'description', 'is_closed', 'need_permission', 'password', 'cover']

    def get_success_url(self):
        return reverse('Chat:Settings', kwargs={'Room_Code': self.room.code})

    def get_object(self, *args, **kwargs):
        self.room.save_old_image_path()
        return self.room
    
    def form_valid(self, form):
        _Room = form.save(commit=False)
        if _Room.get_old_image_name() != form.cleaned_data['cover'] and (
            _Room.get_old_image_name() != 'rooms/defaultCover.jpg'
        ):
            default_storage.delete(_Room.get_old_image_path())

        _Room.password = make_password(form.cleaned_data['password'])
        _Room.last_updated = timezone.now()
        _Room.save()
        return super().form_valid(form)


class MembersView(LoginRequiredMixin, ProfileMixin, RoomMixin, ListView):

    is_admin = True

    def get_queryset(self):
        return Members.objects.filter(room=self.room, is_deleted=False).select_related('user')\
            .prefetch_related('user__profile')


class MemberView(LoginRequiredMixin, ProfileMixin, RoomMixin, MemberMixin, views.JSONResponseMixin, View):

    is_admin = True

    def patch(self, request, Room_Code, Member_id):
        if 'upgrade' in request.GET:
            self.Request_Member.is_admin = True
        else:
            self.Request_Member.is_pending = False
        self.Request_Member.save()
        return self.render_json_response({})


    def delete(self, request, Room_Code, Member_id):
        if self.room.creator == self.Request_Member.user:
            return self.render_json_response({'error': 'Is Creator'}, 403)
        
        elif self.Request_Member.is_admin and not self.is_creator():
            return self.render_json_response({'error': 'Is Admin'}, 403)
        
        if 'degrade' in request.GET:
            self.Request_Member.is_admin = False
        else:
            self.Request_Member.is_deleted = True
            
        self.Request_Member.save()
        return self.render_json_response({}, 204)

Apps/Chat/templates/Chat/Create.html
{% extends 'Chat/shared/base.html' %}

{% block title %} Create Room {% endblock %}

{% block content %}


<br /><br />
<h3 class="text-center">Create Room</h3>
<br /><br />


<form method="post" id="Form" enctype="multipart/form-data">

    {% csrf_token %}

    <div class="form-group row">
        <label for="name" class="col-sm-2 col-form-label">Room Name</label>
        <div class="col-sm-7">
            <input type="text" class="form-control" id="name" name="name" placeholder="Enter Room Name"
                value="{{ form.name.value|default:'' }}" required>
            <div style="color: #dc3545; font-size: 80%;">
                {{ form.name.errors }}
            </div>
        </div>
    </div>

    <div class="form-group row">
        <label for="password" class="col-sm-2 col-form-label">Room password</label>
        <div class="col-sm-7">
            <input type="password" class="form-control" id="password" name="password"
                placeholder="Enter Room Password" required autocomplete="">
            <div style="color: #dc3545; font-size: 80%;">
                {{ form.password.errors }}
            </div>
        </div>
    </div>

    <div class="mb-3">
        <label for="description">Room Description</label>
        <textarea class="form-control col-sm-9" id="description" placeholder="Write Descrption"
            name="description" rows="5">{{ form.description.value }}</textarea>
        <div style="color: #dc3545; font-size: 80%;">
            {{ form.description.errors }}
        </div>
    </div>

    <div class="custom-file">
        <input type="file" class="custom-file-input" id="cover" name="cover">
        <label class="custom-file-label" for="cover">Choose Room Cover</label>
        <div style="color: #dc3545; font-size: 80%;">
            {{ form.cover.errors }}
        </div>
    </div>

    <br /><br />

    <div class="text-center">
        <button class="btn btn-success" type="submit" style="width: 50%;">Create</button>
    </div>
    
</form>


<br /><br /><br />

{% endblock %}

Apps/Chat/templates/Chat/Home.html
{% extends 'Chat/shared/base.html' %}

{% load static %}

{% block title %} Home {% endblock %}

{% block content %}

<br /><br />
<h3 class="text-center">Chat Rooms</h3>
<br /><br />


{% if request.flash_message.exists.create_room %}
    {% include 'Chat/shared/model.html' with ModelMessage=request.flash_message.create_room %}
{% endif %}


{% for room in object_list %}

<div class="card mb-3" style="max-width: 540px;">
    <div class="row no-gutters">
      <div class="col-md-4">
        <img src="{{ room.cover.url }}" alt="Room Cover" style="width: 100%; height: 100%;">
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h5 class="card-title">{{ room.name }}</h5>
          <p class="card-text">{{ room.description }}</p>
          <p class="card-text"><small class="text-muted">Created At {{ room.created_at }}</small></p>
          <a href="{% url 'Chat:Room' room.code %}" class="btn btn-primary">Go To Room</a>
        </div>
      </div>
    </div>
</div>

{% endfor %}

{% endblock %}

Apps/Chat/templates/Chat/Members.html
{% extends 'Chat/shared/base.html' %}
{% load static %}

{% block title %} Room Members {% endblock %}

{% block styles %}
<link href="{% static 'Chat/css/Members.css' %}" rel="stylesheet" />
{% endblock %}

{% block content %}

<br /><br />
<h3 class="text-center">Room Members</h3>
<br /><br />

{% csrf_token %}


<div class="row">
    {% for Member in object_list %}
    <div class="col-md-3 col-xs-6 col-xss-12" id="{{ Member.id }}">
        <div class="member text-center">
            <div class="member-top">
                <figure>
                    <img src="{{ Member.user.profile.avatar.url }}" alt="Member Profile Avatar">
                </figure>
            </div><!-- End .member-top -->
            {% if Member.is_pending %}
                <a href="javascript:void(0);" class="Pending"
                Pending-Url="{% url 'Chat:Member' room.code Member.id %}" style="color: green;">Approve</a>
                <br />
            {% elif Member.is_admin == False %}
                <a href="javascript:void(0);" class="Upgrade" User-id="{{ Member.id }}"
                Upgrade-Url="{% url 'Chat:Member' room.code Member.id %}?upgrade=true"
                style="color: green;">Upgrade To Admin</a>
                <br />
            {% else %}
                <a href="javascript:void(0);" class="Degrade" User-id="{{ Member.id }}"
                Degrade-Url="{% url 'Chat:Member' room.code Member.id %}?degrade=true"
                style="color: red;">Degrade From Admin</a>
                <br />
            {% endif %}
            <a href="javascript:void(0);" class="Kick-Out" User-id="{{ Member.id }}"
                Kick-Out-Url="{% url 'Chat:Member' room.code Member.id %}" style="color: red;">Kick Out</a>
            <h3 class="member-title"><a href="#">{{ Member.user.get_short_name }}</a> 
                <small>({% if room.creator == Member.user %}Co-founder{% elif Member.is_admin %}Admin{% elif Member.is_pending %}Pending{% else %}Member{% endif %})</small>
            </h3>
            <p>{{ Member.user.profile.bio|default:'' }}</p>
        </div><!-- End .member -->
    </div><!-- End .col-md-3 -->
    {% endfor %}
</div>
{% endblock %}


{% block scripts %}
<script>
    document.addEventListener('DOMContentLoaded', () => {

        function ApproveUrl(_Approve_Url, target){

            $.ajax(_Approve_Url , {

                type: 'PATCH',

                headers: { 
                    "X-CSRFToken": document.getElementsByName('csrfmiddlewaretoken')[0].value
                },

                dataType: 'json',

                success: function (data, status, xhr) {

                    console.log(data)
                    console.log(status)
                    console.log(xhr)

                    target.remove()
                },

                error: function (jqXhr, textStatus, errorMessage) {
                    console.log(errorMessage);
                    console.log(textStatus);
                    console.log(jqXhr);
                    alert(jqXhr.responseJSON?.Result);
                }
            });
        }

        function DeleteUrl(_Delete_Url, target){

            $.ajax(_Delete_Url , {

                type: 'DELETE',

                headers: { 
                    "X-CSRFToken": document.getElementsByName('csrfmiddlewaretoken')[0].value
                },

                dataType: 'json',

                success: function (data, status, xhr) {

                    console.log(data)
                    console.log(status)
                    console.log(xhr)

                    target.remove();
                },

                error: function (jqXhr, textStatus, errorMessage) {
                    console.log(errorMessage);
                    console.log(textStatus);
                    console.log(jqXhr);

                    console.log(jqXhr.responseJSON?.error)
                    alert(jqXhr.responseJSON?.error)
                }
            });
        }

        document.querySelectorAll('.Kick-Out').forEach(element => {
            element.onclick = (event) => {
                event.preventDefault();

                _Delete_Url = event.target.getAttribute('Kick-Out-Url');
                if (!_Delete_Url){
                    return
                }

                if (confirm('Are You Sure You Want To Kick User Out?')){
                    DeleteUrl(_Delete_Url, document.getElementById(event.target.getAttribute('User-id')));
                }

            }
        });

        document.querySelectorAll('.Degrade').forEach(element => {
            element.onclick = (event) => {
                event.preventDefault();

                _Degrade_Url = event.target.getAttribute('Degrade-Url');
                if (!_Degrade_Url){
                    return
                }

                if (confirm('Are You Sure You Want To Degrade User From Admin?')){
                    DeleteUrl(_Degrade_Url, element);
                }

            }
        });


        document.querySelectorAll('.Pending').forEach(element => {
            element.onclick = (event) => {
                event.preventDefault();

                _Approve_Url = event.target.getAttribute('Pending-Url');
                if (!_Approve_Url){
                    return
                }
                
                if (confirm('Are You Sure You Want To Approve User?')){
                    ApproveUrl(_Approve_Url, element);
                }
            }
        });


        document.querySelectorAll('.Upgrade').forEach(element => {
            element.onclick = (event) => {
                event.preventDefault();

                _Approve_Url = event.target.getAttribute('Upgrade-Url');
                if (!_Approve_Url){
                    return
                }

                if (confirm('Are You Sure You Want To Upgrade User To Admin?')){
                    ApproveUrl(_Approve_Url, element);
                }
            }
        });

    }, false);
</script>
{% endblock %}

Apps/Chat/templates/Chat/Settings.html
{% extends 'Chat/shared/base.html' %}

{% block title %} {{ room.name }} {% endblock %}

{% block content %}

{% if request.flash_message.exists.update_room %}
    {% include 'Chat/shared/model.html' with ModelMessage=request.flash_message.update_room %}
{% endif %}

<br /><br />
<h3 class="text-center">Room Settings</h3>
<br /><br />

<form method="post" id="Form" enctype="multipart/form-data">

    {% csrf_token %}

    <div class="form-group row">
        <label for="name" class="col-sm-2 col-form-label">Room Name</label>
        <div class="col-sm-7">
            <input type="text" class="form-control" id="name" name="name" placeholder="Enter Room Name"
                value="{{ form.name.value|default:'' }}" required>
            <div style="color: #dc3545; font-size: 80%;">
                {{ form.name.errors }}
            </div>
        </div>
    </div>

    <div class="form-group row">
        <label for="password" class="col-sm-2 col-form-label">Room password</label>
        <div class="col-sm-7">
            <input type="password" class="form-control" id="password" name="password" placeholder="Write The Same Password">
            <div style="color: #dc3545; font-size: 80%;">
                {{ form.password.errors }}
            </div>
        </div>
    </div>

    <div class="mb-3">
        <label for="description">Room Description</label>
        <textarea class="form-control col-sm-9" id="description" placeholder="Write Descrption"
            name="description" rows="5">{{ form.description.value }}</textarea>
        <div style="color: #dc3545; font-size: 80%;">
            {{ form.description.errors }}
        </div>
    </div>

    <br />

    <div class="form-group row">
        <div class="col-sm-10">
            <div class="form-check">
                <input class="form-check-input" type="checkbox" id="is_closed" name="is_closed"
                {% if form.is_closed.value %}checked{% endif %}>
                <label class="form-check-label" for="is_closed">
                  Is Room Closed
                </label>
            </div>
            <div class="form-check">
                <input class="form-check-input" type="checkbox" id="need_permission" name="need_permission"
                {% if form.need_permission.value %}checked{% endif %}>
                <label class="form-check-label" for="need_permission">
                  Does Joining Room Need Permission ?
                </label>
            </div>
        </div>
    </div>

    <div class="custom-file">
        <input type="file" class="custom-file-input" id="cover" name="cover">
        <label class="custom-file-label" for="cover">Choose Room Cover</label>
        <div style="color: #dc3545; font-size: 80%;">
            {{ form.cover.errors }}
        </div>
    </div>

    <br /><br />

    <div class="text-center">
        <button class="btn btn-success" type="submit" style="width: 50%;">Update</button>
    </div>
    
</form>


{% endblock %}