Apps/Auth/urls.py
from django.urls import path
from Apps.Auth import views



app_name = 'Auth'

urlpatterns = [

    path('signup/', views.Signup.as_view(template_name='Auth/signup.html'), name='Signup'),
    path('confirm-signup/', views.ConfirmSignup.as_view(template_name='Auth/confirm-signup.html'), name='Confirm-Signup'),

    path('login/', views.Login.as_view(template_name='Auth/login.html'), name='Login'),
    path('login-as-guest/', views.LoginAsGuest.as_view(), name='Guest-Login'),
    path('logout/', views.Logout.as_view(), name='Logout'),

    path('forget-password/', views.ForgetPassword.as_view(template_name='Auth/forget-password.html'), name='Forget-Password'),
    path('reset-password/', views.ResetPassword.as_view(template_name='Auth/reset-password.html'), name='Reset-Password'),
]

Apps/Chat/urls.py
from django.urls import path, include
from . import views



app_name = 'Chat'

urlpatterns = [

    path('create/', views.CreateRoomView.as_view(template_name='Chat/Create.html'), name='Create'),

    path('room/', views.JoinRoomView.as_view(), name='Join-Room'),

    path('<slug:Room_Code>/', include([

        path('settings/', views.SettingsView.as_view(template_name='Chat/Settings.html'), name='Settings'),

        path('members/', include([

            path('<int:Member_id>/', views.MemberView.as_view(), name='Member'),

            path('', views.MembersView.as_view(template_name='Chat/Members.html'), name='Members'),
        ])),

        path('', views.RoomView.as_view(template_name='Chat/Room.html'), name='Room'),
    ])),
    
    path('', views.HomeView.as_view(template_name='Chat/Home.html'), name='Home')
]

Apps/Info/api/urls.py
from django.urls import path
from . import views


app_name = 'Info.api'

urlpatterns = [

    path('feedback/', views.FeedbackAPI.as_view(), name='Feedback'),
]

Apps/Info/urls.py
from django.urls import path
from . import views


app_name = 'Info'

urlpatterns = [

    path('feedback/', views.FeedbackView.as_view(template_name='Info/Feedback.html'), name='Feedback'),

    path('who-i-am/', views.WhoIAmView.as_view(template_name='Info/WhoIAm.html'), name='WhoIAm'),

    path('download-cv/', views.DownloadCV.as_view(), name='Download-CV'),
]

WebChat/urls.py
import os
from django.apps import apps
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from Apps.Info import views


urlpatterns = [
    path('admin/', admin.site.urls),

    path('auth/', include('Apps.Auth.urls')),

    path('profile/', include('Apps.Profile.urls')),

    path('info/', include('Apps.Info.urls')),

    path('chats/', include('Apps.Chat.urls')),

    path('api/', include([

        path('auth/', include('Apps.Auth.api.urls')),

        path('profile/', include('Apps.Profile.api.urls')),

        path('info/', include('Apps.Info.api.urls')),

        path('chats/', include('Apps.Chat.api.urls')),

    ])),

    path('', views.HomeView.as_view(template_name='Info/Home.html'), name=''),
]

urlpatterns += static(
    settings.MEDIA_URL + 'user/',
    document_root=os.path.join(apps.get_app_config('Profile').path, 'media', 'user'),
)

urlpatterns += static(
    settings.MEDIA_URL + 'rooms/',
    document_root=os.path.join(apps.get_app_config('Chat').path, 'media', 'rooms'),
)

Apps/Info/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _



class Feedback(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(_('Feedback Title'), max_length=100)
    feedback = models.CharField(_('Feedback'), max_length=1000)
    is_deleted = models.BooleanField(_('Is Feedback Deleted'), default=False)
    created_at = models.DateTimeField(_('Feedback Creation Date'), auto_now_add=True)

Apps/Info/api/views.py
from rest_framework.generics import CreateAPIView
from rest_framework import exceptions
from .serializers import FeedbackSerializer
from .mixins import BaseMixin
import os


class FeedbackAPI(BaseMixin, CreateAPIView):
    throttle_scope = 'feedback', '100/hour'
    serializer_class = FeedbackSerializer

    def perform_create(self, serializer):
        if self.request.user.get_username() == os.environ.get('GUEST_USERNAME'):
            raise exceptions.PermissionDenied(detail='Guest User Can not create feedback')
        serializer.save(user=self.request.user)
        return super().perform_create(serializer)

Apps/Info/views.py
from django.apps import apps
from django.conf import settings
from django.http import HttpResponse
from django.urls import reverse_lazy as reverse
from django.views.generic import TemplateView, CreateView, View
from Apps.Auth.mixins import LoginRequiredMixin, SuccessMessageMixin
from Apps.Profile.mixins import ProfileMixin
from .models import Feedback
import os


class HomeView(ProfileMixin, TemplateView):
    pass

class FeedbackView(LoginRequiredMixin, ProfileMixin, SuccessMessageMixin, CreateView):
    success_flash_message_name = 'success_create_feedback'
    success_flash_message = 'Your Feedback Submitted Successfully'

    success_url = reverse('Info:Feedback')

    model = Feedback
    fields = ['title', 'feedback']

    def form_valid(self, form):
        if self.request.user.get_username() == os.environ.get('GUEST_USERNAME'):
            form.add_error('title', 'Guest User Can Not Make Feedback')
            return super().form_invalid(form)
        _Feedback = form.save(commit=False)
        _Feedback.user = self.request.user
        return super().form_valid(form)

class WhoIAmView(ProfileMixin, TemplateView):
    pass

class DownloadCV(View):

    def get(self, request):
        _File_Path = apps.get_app_config('Info').path + settings.MEDIA_URL + 'Django Backend Developer.pdf'

        with open(_File_Path, 'rb') as pdf:
            response = HttpResponse(pdf.read(), content_type='application/pdf')
            response['Content-Disposition'] = 'inline; filename="Django Backend Developer.pdf"'
            return response

Apps/Info/templates/Info/Feedback.html
{% extends 'Info/base.html' %}
{% load static %}

{% block title %} Feedback {% endblock %}

{% block feedback %} active {% endblock %}

{% block content %}
<form method="post" id="Form" style="padding-bottom: 20px;">

    {% csrf_token %}

    <h2>Make Your Feedback</h2>
    <br />

    {% if request.flash_message.exists.success_create_feedback %}
        <div class="alert alert-success" role="alert">
            {{ request.flash_message.success_create_feedback }}
        </div>
    {% endif %}
    
    <div class="custom-control custom-checkbox mb-3">
        <label for="title">Feedback Title</label>
        <input class="form-control" id="title" name="title" type="text" placeholder="Feedback Title"
            value="{{ form.title.value|default:'' }}" required>
        <ul style="color: #dc3545" id="title-errors">
            {{ form.title.errors }}
        </ul>
    </div>

    <div class="mb-3">
        <label for="feedback">Feedback</label>
        <textarea class="form-control" id="feedback" placeholder="Enter Your Feedback" required rows="5"
            id="feedback" name="feedback">{{ form.feedback.value|default:'' }}</textarea>
        <ul style="color: #dc3545" id="feedback-errors">
            {{ form.feedback.errors }}
        </ul>
    </div>

    <button style="width: 50%;" type="submit" class="btn btn-success">Send</button>
</form>

{% endblock %}


{% block scripts %}
<script src="{% static 'Info/javascript/feedback.js' %}"></script>
{% endblock %}

Apps/Info/templates/Info/Home.html
{% extends 'Info/base.html' %}

{% block title %} Home Page {% endblock %}

{% block isHomeActive %} active {% endblock %}

{% block content %}
    
    <main role="main" class="inner cover">
        <h1 class="cover-heading">Chat App</h1>
        <p class="lead">Application For Messages Chat.</p>
        <p class="lead">Made Using Django, Django Rest API And Django Channels.</p>
    </main>

{% endblock %}

Apps/Info/templates/Info/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <link rel="icon" href="{% static 'Info/images/favicon.ico' %}">
    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      body {
        position: relative;
      }
      
      .background{
        opacity: 0.6;
        position: absolute;
        left: 0;
        top: 0;
        width: 100%;
        height: auto;
      }

      .padding{
          padding-top: 200px;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link href="{% static 'Info/css/Home.css' %}" rel="stylesheet">
</head>

<body class="text-center">

    <div class="cover-container w-100 h-100 p-3 mx-auto flex-column">
        <header class="masthead mb-auto">
            <div class="inner">
            <h3 class="masthead-brand">Chat App</h3>
            <nav class="nav nav-masthead justify-content-center">
                
                <a class="nav-link {% block isHomeActive %}{% endblock %}"
                    {% if request.user.is_authenticated %}
                        href="{% url 'Chat:Home' %}">Chat Dashboard
                    {% else %}
                        href="{% url 'Auth:Login' %}">Login
                    {% endif %}
                </a>

                <a class="nav-link {% block feedback %}{% endblock %}" href="{% url 'Info:Feedback' %}">Feedback</a>
                <a class="nav-link {% block whoIAm %}{% endblock %}" href="{% url 'Info:WhoIAm' %}">Who I Am</a>
            </nav>
            </div>
        </header>

        <div class="padding"></div>

        {% block content %}{% endblock %}
    </div>

    {% block scripts %}{% endblock %}

</body>
</html>